// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wsrkxjpiynrbhnherwmj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indzcmt4anBpeW5yYmhuaGVyd21qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MjAzOTQsImV4cCI6MjA2MTQ5NjM5NH0.Xtam-wa3CPN-rbEYLtFQnQC5PWHdljf3B271qHZ4lAQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);